### ISSUE TITLE
Controlling Domestic Hot Water Tank through automation

### ISSUE THREAD

**Issue by Jozo81** [tadasdanielius/daikin_altherma#106]
Hello, 

Automatons lost ability to turn on/off hot water tank after 2024.9 update. Manual controls works as before. Also floor heating can be controlled through automations as before.

When running the action, comes following error:
Error running action
Entity water_heater.domestic_hot_water_tank does not support this service.

**Comment by tadasdanielius** [comment]
just checked the action in developer tools

```
action: water_heater.set_operation_mode
target:
  entity_id: water_heater.domestic_hot_water_tank
data:
  operation_mode: "on"
```

It worked ok. How does your automation looks like and what you are trying to set?

**Comment by Jozo81** [comment]
Checked also the action in developer tools and it works perfectly. My automation has worked for a long time before something changed. I have a slider to choose how many hours I want to heat and heater turns on and off choosing the cheapest Nordpool hours.

Automation created for floor heating with same parameters works as before.

```
alias: "Nordpool DHW Heating "
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.nordpool_mwh_ee_eur_3_095_02
    attribute: current_price
  - platform: state
    entity_id:
      - input_number.slider24
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.nordpool_mwh_ee_eur_3_095_02
        attribute: current_price
        below: sensor.switching_limit
    then:
      - device_id: xxxx
        domain: water_heater
        entity_id: xxxx
        type: turn_on
    else:
      - device_id: xxxx
        domain: water_heater
        entity_id: xxxx
        type: turn_off
mode: single

```

**Comment by Jozo81** [comment]
Got it work by changing "then" and "else"  

 ``` 
    then:
      - action: water_heater.set_operation_mode
        target:
          entity_id: water_heater.domestic_hot_water_tank
        metadata: {}
        data:
          operation_mode: "on"
    else:
      - action: water_heater.set_operation_mode
        target:
          entity_id: water_heater.domestic_hot_water_tank
        metadata: {}
        data:
          operation_mode: "off"
 ``` 

Don´t know what broke old automation, but this way works again. Thanks for help @tadasdanielius and for great Custom Component (one of the most important ones in my setup)!
