### ISSUE TITLE
Concurrent call to receive() is not allowed

### ISSUE THREAD

**Issue by andreytse** [tadasdanielius/daikin_altherma#23]
When I am using in my automation switch.climate_control for switch on/off
```
action:
  - service: switch.turn_{{ trigger.to_state.state }}
    target:
      entity_id: switch.climate_control
```

I receve in logs ERROR (MainThread) [custom_components.daikin_altherma] Unexpected error fetching daikin_altherma_coordinator data: Concurrent call to receive() is not allowed

What can it be?

**Comment by tarmor1** [comment]
> When I am using in my automation switch.climate_control for switch on/off

Same here but looks not all the time. V.1.2.1
My script:
```
alias: DWH Off
sequence:
  - service: water_heater.set_operation_mode
    data:
      operation_mode: 'off'
    target:
      entity_id: water_heater.domestic_hot_water_tank
mode: single
icon: mdi:shower
```
Trace from script run:
```
-- DWH Off (script.dwh_off) turned on
-- Call service water_heater.set_operation_mode on entities water_heater.domestic_hot_water_tank
-- DWH Off (script.dwh_off) turned off
-- Stopped because an error was encountered at 24 May 2022, 19:29:27 (runtime: 0.19 seconds)
-- Concurrent call to receive() is not allowed
```
Nothing extra to log.
