### ISSUE TITLE
Missing temperature sensor for water tank

### ISSUE THREAD

**Issue by matejsp** [tadasdanielius/daikin_altherma#32]
They is no sensor for water tank current temperature and set temperature. Unable to create a graph for it. But it is for indoor and outdoor temperature.
![image](https://user-images.githubusercontent.com/3091122/184701600-8feb91d9-63fd-42a3-ade1-00820d91d12c.png)

And there is some wierd $NULL inside ID.
![image](https://user-images.githubusercontent.com/3091122/184701547-f69306a8-c009-46df-aae5-69690b807fbc.png)

**Comment by tadasdanielius** [comment]
The nulls are weird but water heater should be under `water_heater` domain. Search for `water_heater` in entities

<img width="416" alt="image" src="https://user-images.githubusercontent.com/8099860/184883554-ba3313b7-4456-4ff1-8e9a-94f12c1afea3.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/8099860/184883698-ceb5a2a7-1869-4b61-a57e-b26fd54c008b.png">

**Comment by matejsp** [comment]
Yes I can see history on the water heater control, but I cannot add a graph pointing to the water temperature.

For example climate control has various sensors:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/3091122/184888533-80daeec3-bd7d-4603-a1db-d9b71be55301.png">

vs water heater that has only energy available:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3091122/184888613-2e0a3f60-a6de-42f8-9ca8-ddd5e50d92e0.png">

I want to create entities card with header 'graph'
```
type: entities
entities:
  - water_heater.domestic_toplotna_crpalka_voda
title: Toplotna crpalka - Voda
header:
  type: graph
  entity: water_heater.domestic_toplotna_crpalka_voda
```

But I can for climate control:
```
type: entities
entities:
  - switch.climate_control
  - select.operation_mode
  - number.temperature_control
title: Toplotna crpalka
header:
  type: graph
  entity: sensor.indoor_temperature
  detail: 2
  hours_to_show: 168
```

getting:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3091122/184891186-faef70d9-fe62-421f-87f2-488c84ee2572.png">

**Comment by matejsp** [comment]
Another thing is why not using thermostat widget for climate control? Should be better suitable for heat pump?
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3091122/184892292-5fa15f06-3f29-4186-bd3e-013941da4556.png">

Btw. Great work! Love it!

**Comment by tadasdanielius** [comment]
The water tank is implemented as [Water Heater Entity](https://developers.home-assistant.io/docs/core/entity/water-heater/)
You can extract temperature by creating template sensors.
Somewhere in your `configuration.yaml` you can put this (just put the right entity names)

```yaml
template:
  - sensor:
      - name: "Water Tank Target Temperature"
        unit_of_measurement: °C
        device_class: temperature
        state: >
          {{ state_attr('water_heater.domestic_hot_water_tank','temperature') }}

      - name: "Water Tank Current Temperature"
        unit_of_measurement: °C
        device_class: temperature
        state: >
          {{ state_attr('water_heater.domestic_hot_water_tank','current_temperature') }}
```
And you should have sensors which you can plot how you want.

Now regarding the thermostat. At least my device does not provide such thing as "target temperature", I can only control "Leaving water temperature" therefore the default thermostat entity does not play very well, so I created separate entities. But, you can easily wrap it up to [generic_thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)

put somewhere in your `configuration.yaml`
```yaml
climate:
  - platform: generic_thermostat
    name: My Heater
    unique_id: daikin_climate_control
    target_sensor: sensor.your_temperature_sensor
    min_temp: 18
    max_temp: 26
    heater: switch.your_daiking_climate_control
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    ac_mode: false
    initial_hvac_mode: "heat"
    min_cycle_duration:
      seconds: 5
```
