### ISSUE TITLE
First look

### ISSUE THREAD

**Issue by Spitfire69** [tadasdanielius/daikin_altherma#7]
Great integration! 👍

I just added it and it seems to work very well. However I noticed that the indoor temperature at some times had a lot of decimals ie 17,799998 (or something similar).

It would also be nice if you could add a climate integration so a standard HA thermostat card could be used to set and read the temperature.

Thanks and keep up the good work!

**Comment by tadasdanielius** [comment]
I will into indoor temperature rounding.

Regarding climate integration, the problem is that heat pump does not have desired temperature setting. You can control fixed leaving water temperature which normally is higher than what you want to have in the room (or colder if you are cooling), or you can set the reference temperature based on outside temperature. That makes it tricky to simply use climate integration. But here is a simple workaround to use [generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)

Put this into your configuration.yaml:

```yaml
climate:
  - platform: generic_thermostat
    name: My Heater
    unique_id: daikin_climate_control
    target_sensor: sensor.indoor_temperature
    min_temp: 18
    max_temp: 26
    heater: switch.climate_control
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    ac_mode: false
    initial_hvac_mode: "heat"
    min_cycle_duration:
      seconds: 5
``` 

`target_sensor` and `heater` can be any switch and not necessarily daikin's. 
I will probably add it to documentation
