### ISSUE TITLE
Unable to set with input_number.set_value

### ISSUE THREAD

**Issue by christianreiss** [tadasdanielius/daikin_altherma#82]
Hey,

somewhere in the past updates of home assistant I can not set the LWT anymore using input_number.set_value. This worked before.:

```
service: input_number.set_value
data_template:
  value: "{{ (states('number.temperature_control') | int - 1) }}"
target:
  entity_id: number.temperature_control
```

```
[homeassistant.helpers.service] Referenced entities number.temperature_control are missing or not currently available
```

I can also no longerselect this target in the gui anymore; Is there a new flag or so in the code missing?

**Comment by tadasdanielius** [comment]
There was no breaking changes introduced. Have you made any changes on the unit? Maybe you have switched to the weather dependent curve or vice/versa? What entities you seen in home assistant when you go to devices?
If you haven't made any changes to the unit, then try to delete device and add again.

**Comment by christianreiss** [comment]
I fixed it just now.

 I swear it was working before. Backup says It was like this a year ago:
 
```
                   - service: input_number.set_value
                    data_template:
                      value: "{{ (states('number.temperature_control') | int - 1) }}"
                    target:
                      entity_id: number.temperature_control
```
This WAS working. Fix:

```
                  - service: number.set_value
                    data_template:
                      value: "{{ (states('number.temperature_control') | int - 1) }}"
                    target:
                      entity_id: number.temperature_control
```

Thanks :)
